name: Deploy to cloudtype
on:
  schedule:
    - cron: '0 20 * * *'
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: extra_bottle/my-project
          stage: main
          yaml: |
            name: clova-iot
            app: node@23
            options:
              ports: "1999"
              install: npm ci              
              start: |
                cat > ./my-client.key <<EOF
                ${{ secrets.KEY }}
                EOF
                
                cat > ./lg-client.crt <<EOF
                ${{ secrets.CERT }}
                EOF
                
                cat > ./AmazonRootCA1.pem <<EOF
                ${{ secrets.CA }}
                EOF
                
                node app.js
              env:
                - name: BTC_MSG
                  secret: BTC_MSG                
                - name: CLIENT_ID
                  secret: CLIENT_ID
                - name: CLOVA_ID
                  secret: CLOVA_ID
                - name: CLOVA_SECRET
                  secret: CLOVA_SECRET
                - name: DRY_MSG
                  secret: DRY_MSG                
                - name: LAUNDRY_MSG
                  secret: LAUNDRY_MSG
                - name: MQTT_HOST
                  secret: MQTT_HOST
                - name: SUB_INBOX
                  secret: SUB_INBOX
                - name: SUB_PUSH
                  secret: SUB_PUSH
                - name: SERVER_PORT
                  secret: SERVER_PORT
                - name: DOMAIN
                  secret: DOMAIN
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
